

Ayush Kamboj

---



---


3P14

---


1024160118

---


CC Lab assignment 5

---



In [1]:
import numpy as np

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: a) Addition of 2 in all the element  b) Multiply 3 with all the elements c) Divide every element by 2

In [2]:
py_list=[10,20,30,40]
n_array=np.array(py_list)
n_array
n_array1=n_array+2
n_array2=n_array*3
n_array3=n_array/2
print(n_array1)
print(n_array2)
print(n_array3)


[12 22 32 42]
[ 30  60  90 120]
[ 5. 10. 15. 20.]


Q.2 Questions on Basic NumPy Array:
1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
2. Find the most frequent value and their indice(s) in the following arrays:
*   x = np.array([1,2,3,4,5,1,2,1,1,1])
*  y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [5]:
list1=[1,2,3,6,4,5]
array=np.array(list1)
print(array)
print(array[::-1])

array2=np.array([1,2,3,4,5,1,2,1,1,1])
array3=np.array([1,1,1,2,3,4,2,4,3,3]);
vals,counts=np.unique(array2,return_counts=True)
vals2,count=np.unique(array3,return_counts=True)
mode_index2=np.argmax(count);
mode_index=np.argmax(counts);
print("mode:",vals[mode_index])
print("Mode ii", vals2[mode_index2])

[1 2 3 6 4 5]
[5 4 6 3 2 1]
mode: 1
Mode ii 1


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
1.   Acces 1st row, 2nd column
2.   Access 3rd row, 1st column


In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[0][1])
print(arr[2][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [9]:
ak=np.array(np.linspace(10,100,25))
print(ak)
print(ak.shape)
print(ak.ndim)
print(ak.size)
print(ak.dtype)
print(ak.nbytes)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
1
25
float64
200


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [10]:
ucs420_ak=np.array([[10,20,30,40],
                   [50,60,70,80],
                   [90,15,20,35]])
print(ucs420_ak)
print("Mean:",np.mean(ucs420_ak))
print("Median:",np.median(ucs420_ak))
print("Max_val:",np.max(ucs420_ak))
print("Min_val:",np.min(ucs420_ak))
print("Unique_elements",np.unique(ucs420_ak))

reshaped_ucs420_ak=ucs420_ak.reshape(4,3)
print("reshaped:",reshaped_ucs420_vk);

resized_ucs420_ak=np.resize(ucs420_ak,(2,3))
print("resized:",resized_ucs420_ak)



[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max_val: 90
Min_val: 10
Unique_elements [10 15 20 30 35 40 50 60 70 80 90]
reshaped: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized: [[10 20 30]
 [40 50 60]]
