---
Ayush Kamboj

---
1024160118

---
3P14

---
CC assingment 6

---




Question 1

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [2]:
corrected_temperature = temperature + 2

fahrenheit = (9/5) * temperature + 32

readings_above_32 = temperature[temperature > 32]

count_above_32 = np.sum(temperature > 32)

print("Original temperatures:", temperature)
print("Corrected temperatures (+2°C):", corrected_temperature)
print("Fahrenheit:", fahrenheit)
print("Readings above 32°C:", readings_above_32)
print("Number of readings above 32°C:", count_above_32)

print("\nExplanation:")
print("Vectorization applies operations to the entire array at once,")
print("while Boolean indexing efficiently selects values meeting a condition.")
print("Both avoid explicit for-loops and are generally faster and more concise.")

Original temperatures: [25 28 31 35 38 27 33 40]
Corrected temperatures (+2°C): [27 30 33 37 40 29 35 42]
Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Readings above 32°C: [35 38 33 40]
Number of readings above 32°C: 4

Explanation:
Vectorization applies operations to the entire array at once,
while Boolean indexing efficiently selects values meeting a condition.
Both avoid explicit for-loops and are generally faster and more concise.


In [3]:
import numpy as np

# Steps recorded by 4 users over 3 days
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Total steps recorded
total_steps = np.sum(steps)

# b. Mean number of steps
mean_steps = np.mean(steps)

# c. Maximum and minimum values
maximum = np.max(steps)
minimum = np.min(steps)

# d. Total steps for each day (axis=0)
daily_totals = np.sum(steps, axis=0)

# e. Total steps for each user (axis=1)
user_totals = np.sum(steps, axis=1)

# f. User/day position containing maximum number of steps
max_position = np.unravel_index(np.argmax(steps), steps.shape)

# Display results
print("a. Total steps:", total_steps)
print("b. Mean steps:", mean_steps)
print("c. Maximum steps:", maximum)
print("   Minimum steps:", minimum)
print("d. Total steps for each day:", daily_totals)
print("e. Total steps for each user:", user_totals)
print("f. Maximum value position (user, day):", max_position)

a. Total steps: 84200
b. Mean steps: 7016.666666666667
c. Maximum steps: 9500
   Minimum steps: 4500
d. Total steps for each day: [26500 27300 30400]
e. Total steps for each user: [18300 24500 14400 27000]
f. Maximum value position (user, day): (np.int64(3), np.int64(2))


Question 2

In [4]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total_steps = np.sum(steps)
mean_steps = np.mean(steps)

maximum = np.max(steps)
minimum = np.min(steps)

daily_totals = np.sum(steps, axis=0)

user_totals = np.sum(steps, axis=1)

max_position = np.unravel_index(np.argmax(steps), steps.shape)

print("a. Total steps:", total_steps)
print("b. Mean steps:", mean_steps)
print("c. Maximum steps:", maximum)
print("   Minimum steps:", minimum)
print("d. Total steps for each day:", daily_totals)
print("e. Total steps for each user:", user_totals)
print("f. Maximum value position (user, day):", max_position)

a. Total steps: 84200
b. Mean steps: 7016.666666666667
c. Maximum steps: 9500
   Minimum steps: 4500
d. Total steps for each day: [26500 27300 30400]
e. Total steps for each user: [18300 24500 14400 27000]
f. Maximum value position (user, day): (np.int64(3), np.int64(2))


Question 3


In [5]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("Original:", original)
print("Subset:", subset)

copied_array = original[1:5].copy()
copied_array[0] = 500

print("Original:", original)
print("Copied array:", copied_array)

arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print("3 x 4 Matrix:\n", matrix)

print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:\n", matrix[1:3, 2:4])

flattened = matrix.flatten()
raveled = matrix.ravel()

print("Flatten:", flattened)
print("Ravel:", raveled)

raveled[0] = 100
print("After modifying ravel:")
print("Original matrix:\n", matrix)
print("Ravel:", raveled)

flattened[1] = 200
print("After modifying flatten:")
print("Original matrix:\n", matrix)
print("Flatten:", flattened)

print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 x 4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
 [[ 7  8]
 [11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After modifying ravel:
Original matrix:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
After modifying flatten:
Original matrix:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten: [  1 200   3   4   5   6   7   8   9  10  11  12]
Shape: (3, 4)
Number of dimensions: 2
Size: 12
Data type: int64


Question 4


In [6]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("a. Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("\nb. X.T:")
print(XT)

XT_X = XT @ X
print("\nc. X.T @ X:")
print(XT_X)

inverse = np.linalg.inv(XT_X)
print("\nd. Inverse of X.T @ X:")
print(inverse)

beta = inverse @ XT @ y
print("\ne. Coefficients (beta):")
print(beta)

print("\nf. Coefficients represent the effect of sleep hours, activity level, and stress level on the assistance score.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("\ng. Predicted assistance score:", predicted_score)

a. Shape of X: (4, 3)
Dimensions of X: 2

b. X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

c. X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

d. Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e. Coefficients (beta):
[-0.15921454  0.14083853 10.06302242]

f. Coefficients represent the effect of sleep hours, activity level, and stress level on the assistance score.

g. Predicted assistance score: 75.27862544779117
